export const DEFAULT_EXERCISES = [
  { id: "1", name: "Присідання", duration: 60, isRest: false, custom: false },
  { id: "2", name: "Випади", duration: 60, isRest: false, custom: false },
  { id: "3", name: "Біг на місці", duration: 60, isRest: false, custom: false },
  {
    id: "4",
    name: "Сідничий місток",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "5",
    name: "Випади у боки",
    duration: 60,
    isRest: false,
    custom: false,
  },
  { id: "6", name: "Ножиці", duration: 30, isRest: false, custom: false },
  { id: "7", name: "Стільчик", duration: 45, isRest: false, custom: false },
  {
    id: "8",
    name: "Ходьба на носках",
    duration: 30,
    isRest: false,
    custom: false,
  },
  { id: "9", name: "Стрибки", duration: 60, isRest: false, custom: false },
  {
    id: "10",
    name: "Підйом на носки",
    duration: 30,
    isRest: false,
    custom: false,
  },

  { id: "11", name: "Планка", duration: 30, isRest: false, custom: false },
  { id: "12", name: "Скручування", duration: 45, isRest: false, custom: false },
  { id: "13", name: "Підйом ніг", duration: 45, isRest: false, custom: false },
  { id: "14", name: "Велосипед", duration: 45, isRest: false, custom: false },

  { id: "15", name: "Супермен", duration: 45, isRest: false, custom: false },
  {
    id: "16",
    name: "Скручування лежачи",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "17",
    name: "Бічні скручування",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "18",
    name: "Вакуум живота",
    duration: 30,
    isRest: false,
    custom: false,
  },
  {
    id: "19",
    name: "Планка з поворотами таза",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "20",
    name: "Нахили в сторони з гантелями",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "21",
    name: "Підйом колін з поворотом корпуса",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "22",
    name: "Маятник ногами лежачи",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "23",
    name: "Планка на ліктях з дотиком стегон",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "24",
    name: "Бічна планка",
    duration: 30,
    isRest: false,
    custom: false,
  },
  {
    id: "25",
    name: "Тазовий місток",
    duration: 45,
    isRest: false,
    custom: false,
  },
  {
    id: "26",
    name: "Планка з витягнутими руками",
    duration: 30,
    isRest: false,
    custom: false,
  },
  { id: "27", name: "Кішка", duration: 30, isRest: false, custom: false },
  {
    id: "28",
    name: "Кішка-корова",
    duration: 30,
    isRest: false,
    custom: false,
  },
  { id: "29", name: "Поза дитини", duration: 30, isRest: false, custom: false },

  { id: "30", name: "Відпочинок", duration: 30, isRest: true, custom: false },
];
